# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2023-05-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20230518_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
