# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2023-05-18 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
