# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2023-05-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
